import json
import logging
from datetime import timezone
from typing import Dict, Iterator, List, NamedTuple, Optional

from fastapi import APIRouter, UploadFile, File, Form, HTTPException, Depends, Query
from fastapi.responses import StreamingResponse

from backend.models.db import SessionLocal, get_db
from backend.models.models import Interaction, User
from backend.services import cloud, knowledge, llm
from backend.services.auth import get_current_user
from backend.services.documents import DocumentError, check_ranges, limit_text, read_document
from backend.services import safety
from backend.services.redflag import EMERGENCY, Triage, carried_forward, triage
from backend.utils.file_utils import get_upload_extension, read_upload

logger = logging.getLogger(__name__)

router = APIRouter()

MAX_MESSAGE_CHARS = 4000
MAX_HISTORY_TURNS = 10
MAX_HISTORY_TURN_CHARS = 6000

# Someone writing this has reached out, and this reply is the one thing the app can get right for
# them. It leads with support rather than with what it cannot do, and every line gives them
# somewhere to go. It is never generated by the model, so its wording cannot drift.
_HELPLINES = (
    "- If you are in immediate danger, call your local emergency number — **112** in India and "
    "across Europe, **911** in the US.\n"
    "- **India:** Tele-MANAS on **14416** or **1800-891-4416**, free and open 24/7. "
    "AASRA on **9152987821**.\n"
    "- **US:** call or text **988**. **UK:** call **111**, or Samaritans on **116 123**.\n"
    "- Anywhere else: **findahelpline.com** lists free, confidential lines by country."
)

CRISIS_REPLY = (
    "I'm really glad you told me, and I'm sorry things are this heavy right now. What you're "
    "feeling deserves real support, from a person who can stay with you through it — more than I "
    "can give you here.\n\n"
    "**Please reach out to one of these now. They are free, confidential, and used to this.**\n\n"
    + _HELPLINES +
    "\n\nIf you can, tell someone you trust today — a friend, a family member, your doctor — even "
    "just that you're not okay. You do not have to explain it well, and you do not have to go "
    "through this on your own.\n\n"
    "If you have already taken something, please treat it as an emergency and call your emergency "
    "number now."
)

# Asking how much of a medicine is lethal. The person may be in crisis or may not be, so this
# declines the number without presuming, and still puts help in front of them.
LETHALITY_REPLY = (
    "I can't help with how much of a medicine would be dangerous or fatal — that isn't something "
    "I'll give out, whatever it's for.\n\n"
    "If you're asking because you're thinking about hurting yourself, please talk to someone now. "
    "They are free, confidential, and used to this:\n\n"
    + _HELPLINES +
    "\n\nIf someone has already taken too much, treat it as an emergency: call your emergency "
    "number or your local poison control centre straight away, even if they seem fine.\n\n"
    "If you meant something else — side effects, whether a medicine is safe for you, or what it's "
    "used for — ask me that and I'll help."
)

# Added under a reply to someone describing distress. Appended rather than left to the model, so
# that whether a struggling person is told where to get help does not depend on a 1.5B model
# remembering to mention it.
DISTRESS_FOOTER = (
    "💙 If this has been going on for a while, or it's getting harder to manage, please talk to "
    "your doctor — this is treatable, and you don't have to sort it out alone. If you ever feel "
    "unsafe, free confidential help is available any time: **Tele-MANAS 14416** (India), "
    "**988** (US), **116 123** (UK), or **findahelpline.com** anywhere else."
)

EMERGENCY_REPLY = (
    "⚠️ Your message mentions symptoms that may be an emergency (**{details}**). "
    "Please seek immediate medical attention or call emergency services."
)

# Closes every emergency reply, and is not left to the model for the same reason the steps are
# not. Measured while building this: asked only not to contradict the first-aid steps, the 1.5B
# model still ended a chest-pain reply with "Stay calm, lie down" - against the steps above it,
# which say to sit down. The prompt was tightened and it stopped, but "stopped in four tries out
# of four" is not a guarantee, and an emergency is the wrong place to rely on one. This line
# costs a second to read and settles which half of the reply wins.
EMERGENCY_FOOTER = (
    "ℹ️ Follow the steps above, and whatever the call handler tells you — they come first."
)

EMPTY_REPLY = "Sorry, I couldn't generate a response to that. Please try rephrasing your question."

NO_TEXT_REPLY = (
    "I couldn't find any readable text in this file. Please upload a clearer image or a PDF with selectable text."
)

# Chat and upload replies are streamed as newline-delimited JSON events, so text appears as the
# local model writes it:
#   {"type": "meta", "redflag": bool} or {"type": "meta", "blocked": true}   (always first)
#   {"type": "status", "text": "..."}   progress note, not part of the reply
#   {"type": "delta", "text": "..."}    the next piece of the reply
#   {"type": "consent_required", "reason": ..., "label": ..., "model": ...}
#       the local model failed and a hosted one is configured; the client asks the user before
#       anything is sent off the machine, then retries with allow_cloud=true
#   {"type": "provider", "provider": "anthropic", "label": ...}  this reply came from the hosted model
#   {"type": "sources", "sources": [{"title", "url", "source"}]}
#       reference passages the answer is grounded in. Sent before the model starts, because
#       retrieval takes milliseconds while reading the passages takes seconds.
# Endpoints are plain `def` so the blocking model calls run in a worker thread.


@router.get("/health")
def health():
    return {"status": "ok"}


@router.get("/status")
def status():
    """Whether the local AI models are installed and reachable, and if a fallback exists."""
    return {**llm.model_status(), "cloud": cloud.describe()}


def _event(**data) -> str:
    return json.dumps(data) + "\n"


def _stream(events: Iterator[str]) -> StreamingResponse:
    # no-transform and X-Accel-Buffering stop the dev server's compression and nginx from buffering the stream
    return StreamingResponse(
        events,
        media_type="application/x-ndjson",
        headers={"Cache-Control": "no-cache, no-transform", "X-Accel-Buffering": "no"},
    )


def _say(parts: List[str], text: str) -> str:
    """Add text to the reply, starting a new paragraph if something was already sent."""
    if parts:
        text = "\n\n" + text
    parts.append(text)
    return _event(type="delta", text=text)


def _emit(stream: Iterator[str], parts: List[str]) -> Iterator[str]:
    """Turn a stream of text into delta events, collecting the text in `parts`."""
    started = False
    for text in stream:
        if started:
            parts.append(text)
            yield _event(type="delta", text=text)
        elif text.strip():
            started = True
            yield _say(parts, text.lstrip())
    if not started:
        # e.g. a "thinking" model that used its whole output budget on reasoning
        yield _say(parts, EMPTY_REPLY)


def _model_reply(
    messages: List[Dict],
    max_tokens: int,
    parts: List[str],
    model: Optional[str] = None,
    allow_cloud: bool = False,
    effort: str = cloud.EFFORT_CHAT,
) -> Iterator[str]:
    """Answer with the local model, falling back to the hosted one only with the user's consent.

    When the local model can't answer and a hosted fallback is configured, this asks rather than
    switching: sending a medical question off the machine is the user's decision to make.
    """
    before = len(parts)
    try:
        yield from _emit(llm.stream_chat(messages, model=model, max_tokens=max_tokens), parts)
        return
    except llm.LLMError as e:
        logger.warning("Local model request failed: %s", e)
        if len(parts) > before:
            # Part of the reply is already on screen, so finish with the error instead of restarting
            yield _say(parts, str(e))
            return
        if not cloud.configured():
            yield _say(parts, str(e))
            return
        if not allow_cloud:
            yield _event(type="consent_required", reason=str(e), **cloud.describe())
            return
        local_error = str(e)

    logger.info("Falling back to the hosted model with the user's consent")
    yield _event(type="provider", **cloud.describe())
    try:
        yield from _emit(cloud.stream_chat(messages, effort=effort), parts)
    except cloud.CloudError as e:
        logger.warning("Hosted model request failed: %s", e)
        yield _say(parts, f"{local_error}\n\nThe hosted model could not answer either: {e}")


def _save_interaction(username: str, message: str, reply: str, redflag: bool = False, details: Optional[str] = None):
    # Uses its own session: a streamed reply finishes after the request's dependencies are cleaned up
    with SessionLocal() as db:
        db.add(Interaction(
            user_message=message,
            assistant_reply=reply,
            redflag=redflag,
            redflag_details=details,
            username=username,
        ))
        db.commit()


def _crisis_response(username: str, message: str, category: str, found: List[str]) -> StreamingResponse:
    """Answer with support instead of asking the model.

    The text is fixed rather than generated: at this moment the app must not depend on what a small
    local model decides to say.
    """
    reply = CRISIS_REPLY if category == safety.SELF_HARM else LETHALITY_REPLY
    _save_interaction(username, message, reply, details=", ".join(found))
    return _stream(iter([_event(type="meta", blocked=True), _event(type="delta", text=reply)]))


def _carry_forward(turns: List[Dict[str, str]]) -> Optional[Triage]:
    """The symptom from the turn just before, for a follow-up that names none of its own.

    Only the turn immediately before, and only when the assistant spoke last: that is the shape of
    someone answering the questions they were asked, and it keeps a symptom mentioned ten turns ago
    from attaching itself to an unrelated question.
    """
    if not turns or turns[-1]["role"] != "assistant":
        return None
    asked_about = [turn for turn in turns if turn["role"] == "user"]
    return carried_forward(asked_about[-1]["text"]) if asked_about else None


def _is_emergency(triaged) -> bool:
    """Whether this message gets the warning and the steps, rather than an ordinary answer."""
    return triaged is not None and triaged.level == EMERGENCY


# Paragraphs the app writes into its own replies rather than the model: the emergency warning and
# steps, the caution safety net, the footers. Sending them back as if the model had written them
# teaches it to write its own - measured, a follow-up produced its own "Call your emergency number
# straight away if..." line immediately above the real one, with worse wording. So they are removed
# from the history before it goes back to the model. The user still sees them; only the model does
# not, which is the point.
_APP_WRITTEN = (
    "⚠️",                                    # EMERGENCY_REPLY
    "**Do this now**",                                  # redflag.CALL_FIRST
    "**While you wait",                                 # redflag.GUIDANCE headings
    "**If someone has collapsed**",
    "**Call your emergency number straight away if**",  # redflag.SAFETY_NET
    "ℹ️",                                    # EMERGENCY_FOOTER
    "💙",                                       # DISTRESS_FOOTER
)


def _without_app_text(reply: str) -> str:
    """Strip the fixed paragraphs the app added, leaving what the model actually wrote."""
    kept = [p for p in reply.split("\n\n") if not p.lstrip().startswith(_APP_WRITTEN)]
    return "\n\n".join(kept).strip()


def _parse_history(raw: Optional[str]) -> List[Dict[str, str]]:
    """Parse the optional JSON list of earlier turns ({"role", "text"}) sent by the client."""
    if not raw:
        return []
    try:
        turns = json.loads(raw)
    except ValueError:
        raise HTTPException(status_code=400, detail="history must be a JSON list of messages.")
    if not isinstance(turns, list):
        raise HTTPException(status_code=400, detail="history must be a JSON list of messages.")

    history = []
    for turn in turns[-MAX_HISTORY_TURNS:]:
        if not isinstance(turn, dict):
            continue
        role, text = turn.get("role"), turn.get("text")
        if role == "assistant" and isinstance(text, str):
            text = _without_app_text(text)
        if role in ("user", "assistant") and isinstance(text, str) and text.strip():
            history.append({"role": role, "text": text[:MAX_HISTORY_TURN_CHARS]})
    return history


def _check_length(text: str):
    if len(text) > MAX_MESSAGE_CHARS:
        raise HTTPException(status_code=400, detail=f"Message is too long (maximum {MAX_MESSAGE_CHARS} characters).")


@router.post("/chat")
def chat(
    message: str = Form(...),
    history: Optional[str] = Form(None),
    # Set by the client only after the user has accepted the hosted model's privacy warning
    allow_cloud: bool = Form(False),
    user: User = Depends(get_current_user),
):
    message = message.strip()
    if not message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")
    _check_length(message)
    turns = _parse_history(history)
    username = user.username

    # Safety layer: self-harm messages get support and helplines instead of a model reply
    category, found_prohibited = safety.classify(message)
    if category:
        return _crisis_response(username, message, category, found_prohibited)

    # Not a crisis, but the person is struggling: answer warmly and end with somewhere to turn
    distress = safety.detect_distress(message)

    # Red-flag detection, at two levels. An emergency gets the warning and what to do about it
    # before anything else; a caution is answered like any other question, with a fixed line at
    # the end about when it would stop being ordinary.
    triaged = triage(message) or _carry_forward(turns)
    emergency = _is_emergency(triaged)
    # An emergency is answered by the stronger model, within a much smaller budget: the part that
    # has to be right is fixed text, and the rest is background someone is waiting on
    model = llm.choose_chat_model(emergency=emergency, caution=triaged is not None and not emergency)
    max_tokens = llm.EMERGENCY_MAX_TOKENS if emergency else llm.CHAT_MAX_TOKENS

    def events():
        parts: List[str] = []
        yield _event(type="meta", redflag=emergency)
        if emergency:
            # Both are fixed text, so they reach the screen in a few milliseconds - before the
            # model has been asked anything, and before it could have written a word
            yield _say(parts, EMERGENCY_REPLY.format(details=triaged.label))
            yield _say(parts, triaged.guidance)

        # Retrieval takes about 30ms, so the citations can be shown straight away. The model then
        # spends seconds reading those passages, and the wait has something to show for it.
        # An emergency skips it: the model would read up to 2600 characters before writing a
        # word, roughly six seconds of CPU, to add background to advice already on the screen.
        passages = [] if emergency else knowledge.search(message)
        if passages:
            yield _event(type="sources", sources=knowledge.sources(passages))
        context = knowledge.build_context(passages) if passages else None
        messages = llm.build_chat_messages(
            message, turns,
            emergency_details=triaged.label if emergency else None,
            emergency_ask=bool(triaged and triaged.ask),
            # The matched phrase rather than the category name: "deep cut" is what they said,
            # and "heavy bleeding" would put the drama back that the level just took out
            caution_details=triaged.details if triaged and not emergency else None,
            context=context, distress=bool(distress),
        )
        yield from _model_reply(messages, max_tokens, parts, model=model, allow_cloud=allow_cloud)
        if emergency:
            yield _say(parts, EMERGENCY_FOOTER)
        elif triaged and parts:
            yield _say(parts, triaged.safety_net)
        if distress and parts:
            yield _say(parts, DISTRESS_FOOTER)
        if parts:
            # A caution is not flagged in the history - it was not one - but the phrases that
            # matched are still recorded, so the classification can be audited either way
            _save_interaction(
                username, message, "".join(parts), redflag=emergency,
                details=triaged.details if triaged else None,
            )

    return _stream(events())


@router.post("/upload")
def upload(
    file: UploadFile = File(...),
    message: Optional[str] = Form(None),
    allow_cloud: bool = Form(False),
    user: User = Depends(get_current_user),
):
    query = (message or "").strip()
    _check_length(query)
    extension = get_upload_extension(file.filename)
    data = read_upload(file)
    try:
        document = read_document(data, extension)
    except DocumentError as e:
        raise HTTPException(status_code=400, detail=str(e))

    username = user.username
    user_message = f"[Uploaded File: {file.filename}]" + (f"\nQuery: {query}" if query else "")

    category, found_prohibited = safety.classify(query)
    if category:
        return _crisis_response(username, user_message, category, found_prohibited)

    triaged = triage(query)
    emergency = _is_emergency(triaged)

    def events():
        parts: List[str] = []
        yield _event(type="meta", redflag=emergency)
        if emergency:
            yield _say(parts, EMERGENCY_REPLY.format(details=triaged.label))
            yield _say(parts, triaged.guidance)

        text = document.text
        if document.images:
            # Scans and photos are read by the vision model first
            yield _event(type="status", text="Reading the document…")
            try:
                text = llm.transcribe_images(document.images)
            except llm.LLMError as e:
                logger.warning("Document transcription failed: %s", e)
                text = None
                if cloud.configured() and not allow_cloud:
                    yield _event(type="consent_required", reason=str(e), **cloud.describe())
                elif allow_cloud and cloud.configured():
                    yield _event(type="provider", **cloud.describe())
                    try:
                        text = cloud.transcribe_images(document.images, llm.TRANSCRIBE_PROMPT, llm.NO_TEXT)
                    except cloud.CloudError as cloud_error:
                        logger.warning("Hosted transcription failed: %s", cloud_error)
                        yield _say(parts, f"{e}\n\nThe hosted model could not read it either: {cloud_error}")
                else:
                    yield _say(parts, str(e))

        if text is not None:
            if text.strip():
                yield _event(type="status", text="Analyzing the report…")
                text = limit_text(text)
                messages = llm.build_document_messages(
                    text, query, emergency_details=triaged.label if emergency else None,
                    range_checks=check_ranges(text),
                )
                # Reports always use the stronger model: reading values against reference ranges
                # is the reasoning the small model is worst at
                yield from _model_reply(
                    messages, llm.DOCUMENT_MAX_TOKENS, parts, model=llm.CHAT_MODEL,
                    allow_cloud=allow_cloud, effort=cloud.EFFORT_DOCUMENT,
                )
            else:
                yield _say(parts, NO_TEXT_REPLY)

        if emergency:
            yield _say(parts, EMERGENCY_FOOTER)
        elif triaged and parts:
            yield _say(parts, triaged.safety_net)

        if parts:
            _save_interaction(
                username, user_message, "".join(parts), redflag=emergency,
                details=triaged.details if triaged else None,
            )

    return _stream(events())


def _isoformat_utc(value):
    if value is None:
        return None
    # SQLite returns naive datetimes; CURRENT_TIMESTAMP is UTC, so label them as UTC
    # so the browser converts them to the user's local time correctly.
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.isoformat()


@router.get("/history")
def history(limit: int = Query(50, ge=1, le=200), user: User = Depends(get_current_user), db=Depends(get_db)):
    """Return the current user's most recent interactions (desc by created_at)."""
    items = (
        db.query(Interaction)
        .filter(Interaction.username == user.username)
        .order_by(Interaction.created_at.desc(), Interaction.id.desc())
        .limit(limit)
        .all()
    )
    results = []
    for it in items:
        results.append({
            "id": it.id,
            "user_message": it.user_message,
            "assistant_reply": it.assistant_reply,
            "redflag": bool(it.redflag),
            "redflag_details": it.redflag_details,
            "created_at": _isoformat_utc(it.created_at),
        })
    return {"items": results}


@router.delete("/history")
def delete_history(user: User = Depends(get_current_user), db=Depends(get_db)):
    db.query(Interaction).filter(Interaction.username == user.username).delete()
    db.commit()
    return {"status": "cleared"}
